# Generated by Django 4.1.5 on 2023-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '机器学习算法管理', 'verbose_name_plural': '机器学习算法管理'},
        ),
        migrations.AddField(
            model_name='project',
            name='project_author',
            field=models.CharField(default=1, max_length=200, verbose_name='项目作者'),
            preserve_default=False,
        ),
    ]
