# Generated by Django 4.1.5 on 2023-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_alter_project_options_project_project_author'),
    ]

    operations = [

        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.SmallIntegerField(choices=[(0, '图片'), (1, '文字'), (2, '其他')], verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_version',
            field=models.CharField(blank=True, max_length=200, verbose_name='项目不确定性'),
        ),
    ]
