# Generated by Django 4.1.5 on 2023-02-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0003_project_project_data_project_project_description_and_more'),
    ]

    operations = [

    ]
