# Generated by Django 4.1.5 on 2023-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_remove_project_project_data_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default=1, max_length=1000, verbose_name='项目描述'),
            preserve_default=False,
        ),
    ]
