# Generated by Django 4.1.5 on 2023-02-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_project_project_data_project_project_description'),
    ]

    operations = [

    ]
