# Generated by Django 4.1.5 on 2023-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0008_remove_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_data',
            field=models.CharField(default=1, max_length=200, verbose_name='上传日期'),
            preserve_default=False,
        ),
    ]
