# Generated by Django 4.1.5 on 2023-02-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0010_remove_project_project_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'ML management', 'verbose_name_plural': 'ML management'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_version',
        ),
        migrations.AddField(
            model_name='project',
            name='Metrological',
            field=models.CharField(default=2, max_length=200, verbose_name='Metrological'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='SingleDetermination',
            field=models.CharField(default=1, max_length=200, verbose_name='SingleDetermination'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='TestParameters',
            field=models.CharField(default=1.0, max_length=200, verbose_name='TestParameters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='TestRequirements',
            field=models.CharField(default=1, max_length=200, verbose_name='TestRequirements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='TestValueError',
            field=models.CharField(default=1, max_length=200, verbose_name='TestValueError'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='TestValues',
            field=models.CharField(default=1, max_length=200, verbose_name='TestValues'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_uncertainty',
            field=models.CharField(default=1, max_length=200, verbose_name='Measurement uncertainty '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_author',
            field=models.CharField(max_length=200, verbose_name='project author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=200, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.SmallIntegerField(choices=[(0, 'photos'), (1, 'words'), (2, 'others')], verbose_name='project type'),
        ),
    ]
