# Generated by Django 4.1.5 on 2023-02-25 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0011_alter_project_options_remove_project_project_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Metrological',
        ),
        migrations.RemoveField(
            model_name='project',
            name='SingleDetermination',
        ),
        migrations.RemoveField(
            model_name='project',
            name='TestParameters',
        ),
        migrations.RemoveField(
            model_name='project',
            name='TestRequirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='TestValueError',
        ),
        migrations.RemoveField(
            model_name='project',
            name='TestValues',
        ),
    ]
