# Generated by Django 4.1.5 on 2023-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0013_project_metrological_project_singledetermination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='run_time',
            field=models.CharField(default='2023-03-13 13:43:38', max_length=100),
        ),
    ]
