# Generated by Django 4.1.5 on 2023-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0014_project_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description',
            field=models.CharField(default='please enter...', max_length=1000, verbose_name='Project Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='test_set',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='train_set',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
