# Generated by Django 4.1.5 on 2023-03-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0015_project_project_description_project_source_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='source_code',
            new_name='source_code_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='test_set',
            new_name='test_set_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='train_set',
            new_name='train_set_url',
        ),
    ]
