# Generated by Django 3.2 on 2023-04-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0015_project_project_description_project_source_code_and_more'),
    ]

    operations = [


        migrations.RemoveField(
            model_name='project',
            name='TestParameters',
        ),
        migrations.AddField(
            model_name='project',
            name='Test_number',
            field=models.CharField(default=10, max_length=200, verbose_name='Test number'),
            preserve_default=False,
        ),
    ]
