# Generated by Django 3.2 on 2023-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0015_project_project_description_project_source_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('phone', models.CharField(max_length=16, verbose_name='电话')),
                ('CustomerID', models.CharField(max_length=16, verbose_name='身份号码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('address', models.CharField(max_length=16, verbose_name='姓名')),
                ('industry', models.CharField(max_length=16, verbose_name='所属行业')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='source_code',
            new_name='source_code_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='test_set',
            new_name='test_set_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='train_set',
            new_name='train_set_url',
        ),
    ]
